from __future__ import annotations
from dataclasses import dataclass, field
from typing import List


@dataclass(frozen=True)
class Report:
    title: str
    sections: List[str] = field(default_factory=list)
    footer: str = ""


class ReportBuilder:
    def __init__(self) -> None:
        self._title = "Untitled"
        self._sections: List[str] = []
        self._footer = ""

    def set_title(self, title: str) -> "ReportBuilder":
        self._title = title
        return self

    def add_section(self, text: str) -> "ReportBuilder":
        self._sections.append(text)
        return self

    def set_footer(self, footer: str) -> "ReportBuilder":
        self._footer = footer
        return self

    def build(self) -> Report:
        return Report(self._title, list(self._sections), self._footer)


class Director:
    def __init__(self, builder: ReportBuilder) -> None:
        self.builder = builder

    def make_short_report(self) -> Report:
        return (
            self.builder
            .set_title("Short Report")
            .add_section("Brief result")
            .set_footer("Generated by Builder")
            .build()
        )
